# Generated by Django 4.2.4 on 2023-09-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('concern', models.CharField(default='', max_length=700)),
                ('status', models.CharField(choices=[('Awaiting', 'Awaiting'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Awaiting', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
            ],
        ),
    ]
